### ISSUE TITLE
Hello guy Where is the actual context

### ISSUE THREAD

**Issue by cartoonkeng** [kORNkin/WU-OCom-Memo#1]

**Comment by kORNkin** [comment]
still waiting for passion 
![com](https://cdn.discordapp.com/attachments/902184210666749984/1234543890594402415/IMG_0470.JPG?ex=66311e18&is=662fcc98&hm=cc2f02515e0b9020b7e6fb5489d3a16f0f40c962eedaa4e0ac490d9916a244bf&)

**Comment by cartoonkeng** [comment]
gone kee moo lmao
